# General Configuration
PROJECT_NAME: "Mr. CrackBot AI"
VERSION: "1.0"

# Data Directories
DATA_DIR: "data"
WORDLISTS_DIR: "data/wordlists"
CAPTURES_DIR: "data/captures"

# Default Wordlist Files
DEFAULT_WORDLIST: "data/wordlists/rockyou2024.txt"
GENERATED_WORDLIST: "data/wordlists/generated.txt"

# Network Configuration
NETWORK_INTERFACE: "wlan0mon"  # Default wireless interface for scanning/attacking
CAPTURE_TIMEOUT: 60  # Timeout for handshake capture in seconds

# Cracking Configuration
HASHCAT_MODE: 2500  # WPA/WPA2 cracking mode
HASHCAT_OPTIONS: "--force --opencl-device-types=1,2"  # Enable GPU (OpenCL) options

# Logging Configuration
LOG_FILE: "mr_crackbot_ai.log"
LOG_LEVEL: "INFO"

# Additional Configurations
ENABLE_GPU: true  # Enable GPU acceleration
MAX_THREADS: 8  # Utilize the Jetson Nano's full threading capability
TEMP_DIRECTORY: "temp"  # Temporary directory for intermediate files
TEMP_DIRECTORY_ENABLED: true  # Ensure temporary directory handling is activated

# Tool Paths
AIRODUMP_PATH: "/usr/bin/airodump-ng"  # Path to airodump-ng; ensure correct installation
AIREPLAY_PATH: "/usr/bin/aireplay-ng"  # Path to aireplay-ng; ensure correct installation
HASHCAT_PATH: "/usr/bin/hashcat"  # Path to hashcat; ensure correct installation

# Wordlist Management
COMBINED_WORDLIST: "data/wordlists/combined_rockyou2024.txt"
WORDLIST_CHUNK_SIZE: 100000  # Number of lines per chunk when splitting large wordlists

# Security Features
ENABLE_SANDBOX: false  # Run in a sandboxed environment for testing
ENFORCE_SAFE_MODE: true  # Disable potentially destructive operations

# User Interface
UI_THEME: "dark"  # Options: light, dark
ENABLE_ANIMATIONS: true  # Enable animations in the UI

# Notifications
SEND_EMAIL_ALERTS: false  # Send email alerts on critical operations
EMAIL_RECIPIENT: "admin@example.com"  # Email recipient for alerts

# Debugging Options
ENABLE_DEBUG_MODE: false  # Enable verbose debugging logs
VERBOSE_OUTPUT: true  # Enable verbose output for CLI operations

# GPU Configuration for Jetson Nano
CUDA_PATH: "/usr/local/cuda"  # Path to the CUDA toolkit installation
GPU_DEVICE_ID: 0  # GPU device ID to use for tasks
GPU_MAX_MEMORY: 90  # Max GPU memory usage percentage
GPU_FORCE_USAGE: true  # Force GPU acceleration where applicable
