# General Configuration
PROJECT_NAME: "Mr. CrackBot AI"
VERSION: "1.0"

# Data Directories
DATA_DIR: "data"
WORDLISTS_DIR: "data/wordlists"
CAPTURES_DIR: "data/captures"

# Default Wordlist Files
DEFAULT_WORDLIST: "data/wordlists/rockyou2024.txt"
GENERATED_WORDLIST: "data/wordlists/generated.txt"

# Network Configuration
NETWORK_INTERFACE: "wlan0mon"
CAPTURE_TIMEOUT: 60

# Cracking Configuration
HASHCAT_MODE: 2500
HASHCAT_OPTIONS: "--force --opencl-device-types=1,2"

# Logging Configuration
LOG_FILE: "mr_crackbot_ai.log"
LOG_LEVEL: "INFO"

# Additional Configurations
ENABLE_GPU: true
MAX_THREADS: 8
TEMP_DIRECTORY: "temp"
TEMP_DIRECTORY_ENABLED: true

# Tool Paths
AIRODUMP_PATH: "/usr/bin/airodump-ng"
AIREPLAY_PATH: "/usr/bin/aireplay-ng"
HASHCAT_PATH: "/usr/bin/hashcat"

# Wordlist Management
COMBINED_WORDLIST: "data/wordlists/combined_rockyou2024.txt"
WORDLIST_CHUNK_SIZE: 100000

# Security Features
ENABLE_SANDBOX: false
ENFORCE_SAFE_MODE: true

# User Interface
UI_THEME: "dark"
ENABLE_ANIMATIONS: true

# Notifications
SEND_EMAIL_ALERTS: false
EMAIL_RECIPIENT: "admin@example.com"

# Debugging Options
ENABLE_DEBUG_MODE: false
VERBOSE_OUTPUT: true

# GPU Configuration for Jetson Nano
CUDA_PATH: "/usr/local/cuda"
GPU_DEVICE_ID: 0
GPU_MAX_MEMORY: 90
GPU_FORCE_USAGE: true



